"use strict";
const test=require("node:test");const assert=require("node:assert/strict");
const {createTeamWriter,WarehouseTeamIngestError}=require("../src/services/footballWarehouse/teamWriter");
const H=`sha256:${"a".repeat(64)}`;
function input(over={}){return{receipt:{runId:"teams-1",sourceUrl:"https://github.com/nflverse/nflverse-data/releases/download/schedules/games.csv",sourceRef:H,sourceBytes:99,sourceRows:3000,metadata:{schema_fingerprint:H,source_columns:["season"],team_rows:2}},teamRows:[{teamId:"omen:team:buf",nflverseAbbr:"BUF",displayName:"Buffalo Bills",firstSeason:1999,lastSeason:2026},{teamId:"omen:team:mia",nflverseAbbr:"MIA",displayName:"Miami Dolphins",firstSeason:1999,lastSeason:2026}],...over};}
function fake({existing=[],run=[],failAt=null,count=2}={}){const calls=[];let released=false;const client={async query(q){calls.push(q);const n=typeof q==="string"?q:q.name;if(n===failAt){const e=new Error("password=secret private-host");e.code="23505";throw e;}if(n==="warehouse-team-existing-v1")return{rows:existing};if(n==="warehouse-team-run-v1")return{rows:run};if(n==="warehouse-team-start-receipt-v1"||n==="warehouse-team-restart-receipt-v1")return{rows:[{id:7}]};if(n==="warehouse-team-stage-count-v1")return{rows:[{row_count:count}]};if(n==="warehouse-team-succeed-receipt-v1")return{rows:[],rowCount:1};return{rows:[],rowCount:1};},release(){released=true;}};return{pool:{async connect(){return client;}},calls,released:()=>released};}
const names=c=>c.map(q=>typeof q==="string"?q:q.name);
test("upserts exactly the configured canonical team set without deleting historical teams",async()=>{const db=fake();const got=await createTeamWriter({pool:db.pool,expectedTeamRows:2}).writeSnapshot(input());assert.equal(got.state,"succeeded");const promote=db.calls.find(q=>q.name==="warehouse-team-promote-v1");assert.match(promote.text,/LEAST/);assert.match(promote.text,/GREATEST/);assert.doesNotMatch(promote.text,/DELETE/i);const done=db.calls.find(q=>q.name==="warehouse-team-succeed-receipt-v1");assert.equal(done.values[1],3000);assert.equal(db.released(),true);});
test("returns unchanged under the global lock",async()=>{const db=fake({existing:[{id:4}]});const got=await createTeamWriter({pool:db.pool,expectedTeamRows:2}).writeSnapshot(input());assert.equal(got.state,"unchanged");assert.deepEqual(names(db.calls),["BEGIN","warehouse-local-transaction-timeouts-v1","warehouse-team-lock-v1","warehouse-team-existing-v1","COMMIT"]);});
test("binds failed-run retry to the exact bytes and sanitizes database failures",async()=>{const retry=fake({run:[{id:3,state:"failed",source_ref:H}]});await createTeamWriter({pool:retry.pool,expectedTeamRows:2}).writeSnapshot(input());assert.ok(names(retry.calls).includes("warehouse-team-restart-receipt-v1"));const bad=fake({run:[{id:3,state:"failed",source_ref:`sha256:${"b".repeat(64)}`}]});await assert.rejects(createTeamWriter({pool:bad.pool,expectedTeamRows:2}).writeSnapshot(input()),e=>e instanceof WarehouseTeamIngestError&&e.code==="run_id_conflict");const failed=fake({failAt:"warehouse-team-promote-v1"});await assert.rejects(createTeamWriter({pool:failed.pool,expectedTeamRows:2}).writeSnapshot(input()),e=>e.code==="23505"&&!/secret|private-host/.test(e.message));assert.ok(names(failed.calls).indexOf("ROLLBACK")<names(failed.calls).indexOf("warehouse-team-failed-receipt-v1"));});
test("rejects incomplete, duplicate, and receipt-mismatched team snapshots before connecting",async()=>{let connects=0;const writer=createTeamWriter({pool:{async connect(){connects++;throw new Error("no");}},expectedTeamRows:2});await assert.rejects(writer.writeSnapshot(input({teamRows:input().teamRows.slice(0,1)})),/exactly 2/);await assert.rejects(writer.writeSnapshot(input({teamRows:[input().teamRows[0],input().teamRows[0]]})),/duplicate/);const bad=input();bad.receipt.metadata.team_rows=1;await assert.rejects(writer.writeSnapshot(bad),/counts/);assert.equal(connects,0);});
test("rejects a receipt for any source other than the exact schedules asset",async()=>{const bad=input();bad.receipt.sourceUrl="https://example.com/games.csv";await assert.rejects(createTeamWriter({pool:{connect(){throw new Error("must not connect");}},expectedTeamRows:2}).writeSnapshot(bad),/allowlisted/);});
test("failed receipt upsert cannot rebind a run id to different source bytes",async()=>{const db=fake({run:[{id:3,state:"failed",source_ref:`sha256:${"b".repeat(64)}`} ]});await assert.rejects(createTeamWriter({pool:db.pool,expectedTeamRows:2}).writeSnapshot(input()),e=>e.code==="run_id_conflict");assert.match(db.calls.find(q=>q.name==="warehouse-team-failed-receipt-v1").text,/source_ref = EXCLUDED\.source_ref/);});
