"use strict";
const test=require("node:test");const assert=require("node:assert/strict");
const {createScheduleWriter,WarehouseScheduleIngestError}=require("../src/services/footballWarehouse/scheduleWriter");
const H=`sha256:${"c".repeat(64)}`;
function row(over={}){return{season:2026,gameId:"2026_01_BUF_MIA",week:1,gameType:"REG",kickoffAt:null,awayTeamId:"omen:team:buf",homeTeamId:"omen:team:mia",awayScore:20,homeScore:17,overtime:false,stadium:"Hard Rock",location:"Miami",roof:"outdoors",surface:"grass",temperatureF:80,windMph:4,awayRestDays:7,homeRestDays:7,divisionGame:true,spreadLine:2.5,totalLine:44,awayMoneyline:110,homeMoneyline:-120,awayCoach:"A",homeCoach:"B",sourceRow:{game_id:"2026_01_BUF_MIA"},...over};}
function input(over={}){return{season:2026,receipt:{runId:"schedule-2026",sourceUrl:"https://github.com/nflverse/nflverse-data/releases/download/schedules/games.csv",sourceRef:H,sourceBytes:999,sourceRows:3000,metadata:{schema_fingerprint:H,source_columns:["season"],selected_rows:1,preseason_rows:50}},gameRows:[row()],...over};}
function fake({existing=[],run=[],failAt=null,count=1,missing=0,dependencies={player_weekly_stats:0,team_weekly_stats:0,weekly_rosters:0,plays:0}}={}){const calls=[];let released=false;const client={async query(q){calls.push(q);const n=typeof q==="string"?q:q.name;if(n===failAt){const e=new Error("postgres://secret@private-host/db");e.code="23503";throw e;}if(n==="warehouse-schedule-existing-v1")return{rows:existing};if(n==="warehouse-schedule-run-v1")return{rows:run};if(n==="warehouse-schedule-start-receipt-v1"||n==="warehouse-schedule-restart-receipt-v1")return{rows:[{id:8}]};if(n==="warehouse-schedule-stage-check-v1")return{rows:[{row_count:count,missing_teams:missing}]};if(n==="warehouse-schedule-dependent-facts-v1")return{rows:[dependencies]};if(n==="warehouse-schedule-succeed-receipt-v1")return{rows:[],rowCount:1};return{rows:[],rowCount:1};},release(){released=true;}};return{pool:{async connect(){return client;}},calls,released:()=>released};}
const names=c=>c.map(q=>typeof q==="string"?q:q.name);
test("stages, validates, and atomically replaces only the requested season",async()=>{const db=fake();const got=await createScheduleWriter({pool:db.pool}).writeSeason(input());assert.deepEqual(got,{state:"succeeded",ingestEventId:8,season:2026,writtenGames:1});const del=db.calls.find(q=>q.name==="warehouse-schedule-delete-season-v1");assert.deepEqual(del.values,[2026]);assert.ok(names(db.calls).indexOf("warehouse-schedule-stage-check-v1")<names(db.calls).indexOf("warehouse-schedule-delete-season-v1"));assert.deepEqual(db.calls.find(q=>q.name==="warehouse-schedule-succeed-receipt-v1").values,[8,3000]);assert.equal(db.released(),true);});
test("returns unchanged under the per-season lock",async()=>{const db=fake({existing:[{id:2}]});const got=await createScheduleWriter({pool:db.pool}).writeSeason(input());assert.equal(got.state,"unchanged");assert.deepEqual(db.calls.find(q=>q.name==="warehouse-schedule-lock-v1").values,["schedules",2026]);assert.equal(names(db.calls).includes("warehouse-schedule-delete-season-v1"),false);});
test("rejects unknown teams before replacement and rolls replacement back on promotion failure",async()=>{const unknown=fake({missing:1});await assert.rejects(createScheduleWriter({pool:unknown.pool}).writeSeason(input()),e=>e.code==="unknown_team");assert.equal(names(unknown.calls).includes("warehouse-schedule-delete-season-v1"),false);const failed=fake({failAt:"warehouse-schedule-promote-v1"});await assert.rejects(createScheduleWriter({pool:failed.pool}).writeSeason(input()),e=>e instanceof WarehouseScheduleIngestError&&e.code==="23503"&&!/secret|private-host/.test(e.message));assert.ok(names(failed.calls).indexOf("ROLLBACK")>names(failed.calls).indexOf("warehouse-schedule-delete-season-v1"));assert.ok(names(failed.calls).indexOf("warehouse-schedule-failed-receipt-v1")>names(failed.calls).indexOf("ROLLBACK"));});
test("refuses schedule correction while any dependent fact family exists",async()=>{for(const family of ["player_weekly_stats","team_weekly_stats","weekly_rosters","plays"]){const dependencies={player_weekly_stats:0,team_weekly_stats:0,weekly_rosters:0,plays:0,[family]:1};const db=fake({dependencies});await assert.rejects(createScheduleWriter({pool:db.pool}).writeSeason(input()),e=>e.code==="dependent_facts_exist");assert.equal(names(db.calls).includes("warehouse-schedule-delete-season-v1"),false);assert.ok(names(db.calls).indexOf("warehouse-schedule-dependent-facts-v1")<names(db.calls).indexOf("ROLLBACK"));}});
test("retries only a failed run bound to the same exact source",async()=>{const retry=fake({run:[{id:4,state:"failed",source_ref:H}]});await createScheduleWriter({pool:retry.pool}).writeSeason(input());assert.ok(names(retry.calls).includes("warehouse-schedule-restart-receipt-v1"));for(const run of [{id:4,state:"succeeded",source_ref:H},{id:4,state:"failed",source_ref:`sha256:${"d".repeat(64)}`}]){const db=fake({run:[run]});await assert.rejects(createScheduleWriter({pool:db.pool}).writeSeason(input()),e=>e.code==="run_id_conflict");assert.equal(names(db.calls).includes("warehouse-schedule-delete-season-v1"),false);}});
test("rejects mismatched counts, duplicate games, cross-season rows, same teams, and unpaired scores before connecting",async()=>{let connects=0;const writer=createScheduleWriter({pool:{async connect(){connects++;throw new Error("no");}}});const badCount=input();badCount.receipt.metadata.selected_rows=2;await assert.rejects(writer.writeSeason(badCount),/counts/);const duplicate=input({gameRows:[row(),row()]});duplicate.receipt.metadata.selected_rows=2;await assert.rejects(writer.writeSeason(duplicate),/duplicate/);await assert.rejects(writer.writeSeason(input({gameRows:[row({season:2025})]})),/must match/);await assert.rejects(writer.writeSeason(input({gameRows:[row({homeTeamId:"omen:team:buf"})]})),/must differ/);await assert.rejects(writer.writeSeason(input({gameRows:[row({homeScore:null})]})),/paired/);assert.equal(connects,0);});
test("preserves the full public source row in staging",async()=>{const db=fake();await createScheduleWriter({pool:db.pool}).writeSeason(input());const staged=JSON.parse(db.calls.find(q=>q.name==="warehouse-schedule-stage-v1").values[0]);assert.deepEqual(staged[0].source_row,{game_id:"2026_01_BUF_MIA"});});
test("rejects a receipt for any source other than the exact schedules asset",async()=>{const bad=input();bad.receipt.sourceUrl="https://example.com/games.csv";await assert.rejects(createScheduleWriter({pool:{connect(){throw new Error("must not connect");}}}).writeSeason(bad),/allowlisted/);});
test("failed receipt upsert cannot rebind a run id to different source bytes",async()=>{const db=fake({run:[{id:4,state:"failed",source_ref:`sha256:${"d".repeat(64)}`} ]});await assert.rejects(createScheduleWriter({pool:db.pool}).writeSeason(input()),e=>e.code==="run_id_conflict");assert.match(db.calls.find(q=>q.name==="warehouse-schedule-failed-receipt-v1").text,/source_ref = EXCLUDED\.source_ref/);});
