"use strict";
const test=require("node:test");const assert=require("node:assert/strict");const crypto=require("node:crypto");
const {adaptTeamWeeklyCsv,sourceUrlForSeason:teamUrl}=require("../src/services/footballWarehouse/teamWeeklySource");
const {adaptWeeklyRosterCsv,sourceUrlForSeason:rosterUrl}=require("../src/services/footballWarehouse/weeklyRosterSource");
const {acquireTeamWeeklySource}=require("../src/services/footballWarehouse/teamWeeklyAcquisition");
const {createTeamWeeklyWriter}=require("../src/services/footballWarehouse/teamWeeklyWriter");
const {createWeeklyRosterWriter}=require("../src/services/footballWarehouse/weeklyRosterWriter");
const hash=(raw)=>`sha256:${crypto.createHash("sha256").update(raw).digest("hex")}`;
test("team adapter retains the full stat line and binds scores to the exact game",()=>{const raw=Buffer.from("team,season,week,season_type,opponent_team,game_id,attempts,epa\nBUF,2026,1,REG,NYJ,g1,34,1.25\n");const out=adaptTeamWeeklyCsv({raw,season:2026,sourceUrl:teamUrl(2026),runId:"team-2026-a",scoresByGameId:new Map([["g1",{homeTeamId:"omen:team:buf",awayTeamId:"omen:team:nyj",homeScore:24,awayScore:17}]])});assert.equal(out.receipt.sourceRef,hash(raw));assert.deepEqual(out.rows[0].stats,{attempts:34,epa:1.25});assert.equal(out.rows[0].pointsFor,24);assert.deepEqual(out.rows[0].sourceRow,{team:"BUF",season:"2026",week:"1",season_type:"REG",opponent_team:"NYJ",game_id:"g1",attempts:"34",epa:"1.25"});});
test("team adapter refuses score/team mismatch and duplicate team weeks",()=>{const raw=Buffer.from("team,season,week,season_type,opponent_team,game_id\nBUF,2026,1,REG,NYJ,g1\n");assert.throws(()=>adaptTeamWeeklyCsv({raw,season:2026,sourceUrl:teamUrl(2026),runId:"x",scoresByGameId:new Map([["g1",{homeTeamId:"omen:team:chi",awayTeamId:"omen:team:nyj"}]])}),/teams do not match/);assert.throws(()=>adaptTeamWeeklyCsv({raw:Buffer.concat([raw,Buffer.from("BUF,2026,1,REG,NYJ,g2\n")]),season:2026,sourceUrl:teamUrl(2026),runId:"x",scoresByGameId:new Map([["g1",{homeTeamId:"omen:team:buf",awayTeamId:"omen:team:nyj"}],["g2",{homeTeamId:"omen:team:buf",awayTeamId:"omen:team:nyj"}]])}),/duplicate team-week/);});
test("roster adapter resolves GSIS only and reports rather than guesses unmatched names",()=>{const raw=Buffer.from("season,week,team,gsis_id,full_name,position,jersey_number,status\n2026,1,BUF,00-1,Same Name,QB,17,ACT\n2026,1,NYJ,,Same Name,WR,9,ACT\n");const out=adaptWeeklyRosterCsv({raw,season:2026,sourceUrl:rosterUrl(2026),runId:"roster-a",playerIdByGsis:new Map([["00-1","omen:player:gsis.00-1"],["Same Name","omen:player:wrong"]])});assert.equal(out.rows.length,1);assert.equal(out.rows[0].playerId,"omen:player:gsis.00-1");assert.equal(out.unmatchedRows,1);assert.equal(out.unmatched[0].reason,"no_gsis_id");assert.equal(out.receipt.sourceRows,2);});
test("bounded acquisition uses only the exact team season asset",async()=>{const raw=Buffer.from("a,b\n1,2\n");let called;const out=await acquireTeamWeeklySource({season:2026,fetchImpl:async(url)=>{called=url;return{status:200,headers:new Headers({"content-type":"text/csv","content-length":String(raw.length)}),body:new ReadableStream({start(c){c.enqueue(raw);c.close();}})};}});assert.equal(called,teamUrl(2026));assert.deepEqual(out.raw,raw);await assert.rejects(acquireTeamWeeklySource({season:2026,sourceUrl:teamUrl(2025),fetchImpl:async()=>{throw new Error("called");}}),/not the allowlisted/);});
function fake({failAt,startRows=[{id:9}],invalidCount=0}={}){const calls=[];const client={async query(q){calls.push(q);const n=typeof q==="string"?q:q.name;if(n===failAt){const e=new Error("postgres://admin:secret@private/db");e.code="23503";throw e;}if(n?.endsWith("-existing-v1"))return{rows:[]};if(n?.endsWith("-start-v1"))return{rows:startRows};if(n?.endsWith("-check-v1"))return{rows:[{row_count:1}]};if(n?.endsWith("-integrity-v1"))return{rows:[{invalid_count:invalidCount}]};return{rows:[],rowCount:1};},release(){}};return{pool:{connect:async()=>client},calls};}
const receipt=(url)=>({runId:"run-a",sourceUrl:url,sourceRef:`sha256:${"a".repeat(64)}`,sourceBytes:20,sourceRows:1,metadata:{}});
test("team and roster writers stage then atomically replace their season under timeouts",async()=>{const t=fake();const team=await createTeamWeeklyWriter({pool:t.pool}).writeSeason({season:2026,receipt:receipt(teamUrl(2026)),rows:[{season:2026,week:1,seasonType:"REG",teamId:"omen:team:buf",opponentTeamId:"omen:team:nyj",gameId:"g1",pointsFor:24,pointsAgainst:17,stats:{epa:1},sourceRow:{team:"BUF"}}]});assert.equal(team.state,"succeeded");assert.ok(t.calls.some(q=>q.name==="warehouse-team_weekly_stats-promote-v1"));assert.ok(t.calls.some(q=>q.name==="warehouse-local-transaction-timeouts-v1"));const r=fake();const roster=await createWeeklyRosterWriter({pool:r.pool}).writeSeason({season:2026,receipt:receipt(rosterUrl(2026)),rows:[{season:2026,week:1,teamId:"omen:team:buf",playerId:"omen:player:gsis.00-1",gameType:"REG",footballPosition:"QB",jerseyNumber:17,sourceRow:{gsis_id:"00-1"}}]});assert.equal(roster.writtenRows,1);assert.ok(r.calls.some(q=>q.name==="warehouse-weekly_rosters-promote-v1"));});
test("team writer rejects a staged score that disagrees with its bound game",async()=>{const db=fake({invalidCount:1});const writer=createTeamWeeklyWriter({pool:db.pool});await assert.rejects(writer.writeSeason({season:2026,receipt:receipt(teamUrl(2026)),rows:[{season:2026,week:1,seasonType:"REG",teamId:"omen:team:buf",opponentTeamId:"omen:team:nyj",gameId:"g1",pointsFor:25,pointsAgainst:17,stats:{},sourceRow:{}}]}),e=>e.code==="stage_integrity_mismatch");const names=db.calls.map(q=>typeof q==="string"?q:q.name);assert.ok(names.includes("ROLLBACK"));assert.ok(!names.includes("warehouse-team_weekly_stats-promote-v1"));});
test("writers validate all rows before connecting and redact database errors",async()=>{let connects=0;const writer=createWeeklyRosterWriter({pool:{connect:async()=>{connects++;throw new Error("postgres://secret@host/db");}}});await assert.rejects(writer.writeSeason({season:2026,receipt:receipt(rosterUrl(2026)),rows:[{season:2026,week:1,teamId:"bad",playerId:"omen:player:x",sourceRow:{}}]}),/teamId is invalid/);assert.equal(connects,0);});
test("writer rolls back before recording a bounded source-bound failure",async()=>{const db=fake({failAt:"warehouse-weekly_rosters-promote-v1"});const writer=createWeeklyRosterWriter({pool:db.pool});await assert.rejects(writer.writeSeason({season:2026,receipt:receipt(rosterUrl(2026)),rows:[{season:2026,week:1,teamId:"omen:team:buf",playerId:"omen:player:gsis.00-1",sourceRow:{}}]}),e=>{assert.equal(e.code,"23503");assert.equal(e.message,"weekly_rosters ingest failed");assert.doesNotMatch(e.message,/secret|private/);return true;});const names=db.calls.map(q=>typeof q==="string"?q:q.name);assert.ok(names.indexOf("ROLLBACK")<names.indexOf("warehouse-weekly_rosters-failed-receipt-v1"));const failed=db.calls.find(q=>q.name==="warehouse-weekly_rosters-failed-receipt-v1");assert.match(failed.text,/source_ref = EXCLUDED\.source_ref/);assert.equal(failed.values[4],`sha256:${"a".repeat(64)}`);assert.equal(failed.values[7],"23503");assert.equal(failed.values[8],"weekly_rosters ingest failed");});
test("a run id conflict cannot rebind a succeeded or different-source receipt",async()=>{const db=fake({startRows:[]});const writer=createTeamWeeklyWriter({pool:db.pool});await assert.rejects(writer.writeSeason({season:2026,receipt:receipt(teamUrl(2026)),rows:[{season:2026,week:1,seasonType:"REG",teamId:"omen:team:buf",opponentTeamId:"omen:team:nyj",gameId:"g1",pointsFor:1,pointsAgainst:0,stats:{},sourceRow:{}}]}),e=>e.code==="run_id_conflict");const start=db.calls.find(q=>q.name==="warehouse-team_weekly_stats-start-v1");assert.match(start.text,/state='failed' AND football\.warehouse_ingest_events\.source_ref=EXCLUDED\.source_ref/);const failed=db.calls.find(q=>q.name==="warehouse-team_weekly_stats-failed-receipt-v1");assert.match(failed.text,/state <> 'succeeded'/);assert.match(failed.text,/source_ref = EXCLUDED\.source_ref/);});
