# =================================================================
# Slops Saloon Fantasy Football MVP - Dockerfile
# Three-stage build:
#   1. client-builder - vite build -> client/dist/  (static SPA)
#   2. api-builder    - npm ci for the Express server
#   3. production     - slim runtime, copies only what's needed
# =================================================================

# --- STAGE 1: Client builder (Vite) ------------------------------
FROM node:20-alpine AS client-builder

# Vite inlines VITE_* env vars at build time, so we accept them as
# build args. docker-compose passes them through from .env.
# Anon key is public-safe; URL is also public.
ARG VITE_SUPABASE_URL
ARG VITE_SUPABASE_ANON_KEY
ARG VITE_API_BASE_URL
ENV VITE_SUPABASE_URL=$VITE_SUPABASE_URL
ENV VITE_SUPABASE_ANON_KEY=$VITE_SUPABASE_ANON_KEY
ENV VITE_API_BASE_URL=$VITE_API_BASE_URL

WORKDIR /app/client
COPY client/package.json ./
# package-lock.json is generated by 'npm install' on the host. If it
# exists copy it for reproducible installs; if not, npm install will
# create one in this layer.
COPY client/package-lock.json* ./
RUN npm install --no-audit --no-fund

# Copy client sources, then build
COPY client/ ./
RUN npm run build


# ---- frontend (Vite) ----
FROM node:22-alpine AS frontend-builder
WORKDIR /app/frontend
COPY frontend/package.json ./
COPY frontend/package-lock.json* ./
RUN npm ci --prefer-offline
COPY frontend/ ./
RUN npm run build


# --- STAGE 2: API builder (Express) ------------------------------
FROM node:20-alpine AS builder

# Install build tools needed for native npm packages
RUN apk add --no-cache python3 make g++

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci --frozen-lockfile

COPY src/ ./src/


# --- STAGE 3: Production -----------------------------------------
FROM node:20-alpine AS production

# Security: non-root user (SY0-701 5.4: least privilege)
RUN addgroup -S ssffmvp && adduser -S ssffmvp -G ssffmvp

WORKDIR /app

# API runtime: node_modules + server source
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/src          ./src
COPY package.json ./

# Built SPA artifacts only (no node_modules, no source jsx)
COPY --from=client-builder /app/client/dist ./client/dist
COPY --from=frontend-builder /app/frontend/dist ./frontend/dist

ENV NODE_ENV=production

USER ssffmvp

EXPOSE 3000

CMD ["node", "src/server.js"]
